### ISSUE TITLE
Auth0 emails need improvements

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/MasterApp#121]
1. There is no clear visual identification that the email comes from Advanced Algos.

2. The TO field shows: AAProduction <no-reply@auth0user.net>

In the rest of transactional emails we are using Advanced Algos Team.

3. The email went to the junk mail folder with a notice from my spam filter:

3.4 FH_DATE_PAST_20XX      The date is grossly in the future.
-0.0 SPF_HELO_PASS          SPF: HELO matches SPF record
 0.0 HTML_MESSAGE           BODY: HTML included in message
 3.6 DCC_CHECK              Listed in DCC (http://rhyolite.com/anti-spam/dcc/)
 0.3 URIBL_GREY             Contains an URL listed in the URIBL greylist
                            [URIs: mandrillapp.com]

![image](https://user-images.githubusercontent.com/13994516/49012569-1676f900-f17a-11e8-903c-172b9794104b.png)

**Comment by bearcanrun** [comment]
Closed in favor of [https://github.com/Superalgos/NotificationsModule/issues/3](https://github.com/Superalgos/NotificationsModule/issues/3)
