### ISSUE TITLE
Auth0: Last time you logged in... not working

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/MasterApp#123]
When clicking Log In, I get the following Auth0 screen:

![image](https://user-images.githubusercontent.com/13994516/49073575-0c650100-f233-11e8-877f-398869bfe410.png)

After clicking the email account button, Auth0 screen goes away and nothing happens (I'm still logged out)

![image](https://user-images.githubusercontent.com/13994516/49073732-61087c00-f233-11e8-8b42-2748cddfc991.png)

**Comment by julian-molina** [comment]
I refreshed and I'm now logged in.

**Comment by bearcanrun** [comment]
Can't be replicated and wee've switched tenants and updated related packages and code due to domain update.

 Feel free to re-open this issue if it happens again. I would recommend opening up the web tools console and seeing if any errors pop up to help further diagnose/recreate the issue.
