### ISSUE TITLE
Exit Platform must also be available while logged out

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/MasterApp#153]
There is a ‘disconnect’ in terms of the two websites: https://superalgos.org/#supermind and https://platform.superalgos.org/

The user can go to the latter from the former URL, but i can’t see any way to go back from https://platform.superalgos.org/ to superalgos.org.

There should be a button somewhere to go back to https://superalgos.org/#supermind

When logged in there exist a sub menu of the profile name EXIT PLATFORM. This should also be present while logged out.

**Comment by matbenitez** [comment]
Linked from the footer logo.
