### ISSUE TITLE
Text on Platform Home Page

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/MasterApp#220]
We need to replace the text welcoming people so that we can point them in the right direction to use the Strategizer. The following text should be replaced with the one I shall offer below:

![image](https://user-images.githubusercontent.com/13994516/56799739-d0ea5500-6819-11e9-8ae6-0a3425bf2168.png)

Desired text:

Welcome to the Superalgos Platform!
TRY OUT THE STRATEGIZER DEMO

Before you begin, please be aware this is an alpha stage deployment. The features available as of today are limited but already functional. However, you may encounter occasional instability and errors.

At this early stage, the focus of the Superalgos Platform is the Strategizer, a tool directed mostly at traders. To try out the Demo version hosted here you will need to Sign Up / Login. Once you are logged in, you will find basic instructions on how to proceed, at this home page (click the Superalgos logo to return to this home page.

If you are a developer, trying out the Strategizer may open your eyes as of what may be achieved with the Strategizer and the Superalgos Platform in general.

The Strategizer is conceived to work with as many indicators and pre programmed strategies as developers are willing to program.

If you wish to set up your own indicators and strategies, please get in touch with us and we'll show you how (give as a shout in the Community Telegram

This is the expected result:

![image](https://user-images.githubusercontent.com/13994516/56803479-021b5300-6823-11e9-8f7f-656deee9fe7a.png)

**Comment by matbenitez** [comment]
Completed
