### ISSUE TITLE
Refreshing the page at https://app.advancedalgos.net/charts  ends with a white screen

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/MasterApp#39]
![image](https://user-images.githubusercontent.com/9479367/47725815-8ff1f900-dc59-11e8-8929-0425ca8aa876.png)

**Comment by bearcanrun** [comment]
Possibly related to AAWeb #[48](https://github.com/AdvancedAlgos/AAWeb/issues/48) and UsersModule #[22](https://github.com/AdvancedAlgos/UsersModule/issues/22)

**Comment by matbenitez** [comment]
Fixed
