### ISSUE TITLE
Put in place a cache invalidation system for client

### ISSUE THREAD

**Issue by nikolabjelo** [Superalgos/MasterApp#55]
We need to put in place cache invalidation so that the client browser knows when it has to download the client app again.

**Comment by Luis-Fernando-Molina** [comment]
How that would work? What use case is this for?

**Comment by nikolabjelo** [comment]
Depending on the cache configuration of a user, right now it can happen that someone see a browser cached version of the App (not of the data, but of the app itself)

Meaning that changes may not be seen by some users. I didn't identify yet exactly what kind of changes triggers a cache reload and what kind doesn't, but for example if I change a word in the header menu, I have to make a hard reload in chrome in order to see it (a simple reload isn't enough)

This can probably be solved by : 
- Adding a "?randomnumber" at the end of the 
<script type="text/javascript" src="/script.js" async=""></script>
element (this would be a webpack configuration. (Random number is regenerated on builds only)
Or by setting up a worker.

**Comment by julian-molina** [comment]
This issue should be prioritized as the charts simply DO NOT LOAD after a deployment unless a hard reload is made.

**Comment by Luis-Fernando-Molina** [comment]
This issue was solved here: https://github.com/Superalgos/CanvasApp/issues/11
